#!/usr/bin/env bash
# Install ndinx web server on our server

# update package list, install nginx, allow through firewall
apt-get -y update
apt-get -y install nginx

# set efault page content
echo "Hello World!" > /var/www/html/index.html

# restart the server to apply changes
service nginx restart
