#!/usr/bin/env bash
# Install ndinx web server on our server

# Update package lists
apt-get -y update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80
echo '
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        echo "Hello World!";
    }
}
' > /etc/nginx/sites-available/default

# Restart nginx without using systemctl
service Nginx restart