#!/usr/bin/env bash
# Install server THEN perform redirection to another page

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# redirection
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/andrewkimjoseph permanent;/" /etc/nginx/sites-available/default

# restart nginx
service nginx restart
