#!/usr/bin/env bash
# script for the famous fizzbuzz challenge
# dispays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

for ((i = 1; i <= 100; i++)); do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then # multiple of 3 & 5
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then # multiple of 3
		echo "Fizz"
	elif ((i % 5 == 0)); then # muliple of 5
		echo "Buzz"
	else
		echo "$i"
	fi
done
