#!/usr/bin/env bash
# print best school 10 times using a while loop

i=0;
while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++)) # increment counter
done
