#!/usr/bin/env bash
# script that loops 10 times printing Best School....\
# for 4th iteration, prints bad luck
# for 8th iteration, prints good luck

i=1
while [ $i -le 10 ]; do # i less than or equal to 10
	if [ $i -eq 4 ]; then # i equal to 4
		echo "bad luck"
	elif [ $i -eq 8 ]; then # i equal to 8
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++)) # increment i
done
