#!/usr/bin/env bash
# displays numbers from 1 to 10
# 4 followed by bad luck from China - 4th iteration
# 9 followed by bad luck from Japan -> 9th iteration
# 17 followed by bad luck from Italy -> 17th iteration

i=1
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "bad luck form China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck form Italy"
			;;
		*)
			echo "$i"
			;;
	esac

	((i++))
done
