#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
#      - display hours from 0 to 12
#      - displays minutes from 1 to 59

hour=0
minute=1
while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	while [ $minute -le 59 ]; do
		echo "$minute" # display time
		((minute++)) # increment minute
	done
	minute=1 # reset minute
	((hour++)) # increment hour
done
