#!/usr/bin/env bash
# script that displays the content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

for file in *; do # iterate through all files in current dir

	# ensure file is regular file (not a dir or a hidden file)
	if [ -f "$file" ] && [[ "$file" != .* ]]; then
		# use cut to extract relevant part
		name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name_after_dash"
	fi
done
