#!/usr/bin/env bash
# script that checks if fiel "School" exists and prints relevant output

if [ -e "school" ]; then
	echo "school file exists"

	# check if file is empty / not (-s flag)
	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# check if file is a regular file / not (-f flag)
	if [ -f "school" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
